---
title: "General Social Survey US_MLR"
author: "Ismail Khalil"
date: "6/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We will try to predict the highest level of highschool completed by a person based on the highest level of education completed by the father, whether or not the person is born in the US, and their age. 

```{r}
#Load the Data
GSS_data <- read_excel("GSS Clean Final Version Ismail.xlsx")

#Some cleaning 
#Age of respondent have characters in some cells ("89 or older") gonna get rid of that 

GSS_data <- GSS_data %>% 
  mutate(age_numeric = parse_number(age_of_respondent))

GSS_data$highest_year_school_completed_father <- as.numeric(GSS_data$highest_year_school_completed_father)




ggplot(data = GSS_data) + 

geom_point(aes(y = highest_year_of_school_completed, 
               x = high_scool_father))

```


```{r}
model1 <- lm(highest_year_of_school_completed ~ highest_year_school_completed_father , data = GSS_data)
```

